### ISSUE TITLE
Stáhni kilometráž - chyba při nedostupnosti stranky s parametrem foto

### ISSUE THREAD

**Issue by TomasMar** [msehnout/msehnout.github.io#1]
Narazil jsem na problém např. u řeky: http://www.raft.cz/italie/rienza.aspx?ID_reky=106&kilo=kilom
Dočasně vyřešeno odebráním parametru "&kfoto=1&"
Oskar

**Comment by msehnout** [comment]
Hmm.. je to divny. S parametrem &foto to funguje, ale s &kfoto ne. Každopádně jsem tam přidal jednu podmínku, která zkontroluje jestli nastala tadle chyba a kdyžtak to stáhne bez toho.

Fixed in: 463df6a
